<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/CanKit.Pro.CANopen/CanKit.Pro.CANopen.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CanKit.Core" />
    <PackageReference Include="CanKit.Adapter.Virtual" />
  </ItemGroup>

</Project>
